package me.fang.kosh.exceptions

/**
 * Исключение, которое выбрасывает команда `exit` при выполнении
 */
class ExitCalledException : RuntimeException()
